### ISSUE TITLE
Wrong reference for tree-sitter-vue

### ISSUE THREAD

**Issue by stephane303** [Gregoor/tree-sitter-wasms#47]
In your package.json, you point to the original tree-sitter-vue, which has not been updated in years, and does not work anymore.

You should use the official repo from tree-sitter-grammars.

"tree-sitter-vue": "https://github.com/tree-sitter-grammars/tree-sitter-vue#7e48557b903a9db9c38cea3b7839ef7e1f36c693",

**Comment by Gregoor** [comment]
Thank you, I remember being confused when I looked at the dates of that repo but I must have not seen the other one. I will patch this, next time I look at it.

**Comment by Gregoor** [comment]
Fixed in 0.1.11
